### ISSUE TITLE
not working with blender 3.x? or macOS?

### ISSUE THREAD

**Issue by tcurdt** [edzop/bpyhullgen#4]
When I am running the tests they all seem to fail in similar way.

```
$ /Applications/Blender.app/Contents/MacOS/Blender -P "./hull_test_37.py"
Read prefs: /Users/tcurdt/Library/Application Support/Blender/3.0/config/userpref.blend
Integrate
Error: 'assets/actors.blend/Collection/': not a library
Traceback (most recent call last):
  File "/Users/tcurdt/Library/Application Support/Blender/3.0/scripts/addons/bpyhullgen/tests/./hull_test_37.py", line 249, in <module>
    the_hull.integrate_components()
  File "/Users/tcurdt/Library/Application Support/Blender/3.0/scripts/addons/bpyhullgen/hullgen/hull_maker.py", line 355, in integrate_components
    self.integrate_props()	
  File "/Users/tcurdt/Library/Application Support/Blender/3.0/scripts/addons/bpyhullgen/hullgen/hull_maker.py", line 312, in integrate_props
    ob=prop.import_object(view_collection_props)
  File "/Users/tcurdt/Library/Application Support/Blender/3.0/scripts/addons/bpyhullgen/hullgen/prop_helper.py", line 37, in import_object
    bpy.ops.wm.link(directory=full_import_path,
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: 'assets/actors.blend/Collection/': not a library

```

This is what I got for test 37.

<img width="812" alt="Screenshot 2022-02-21 at 23 59 41" src="https://user-images.githubusercontent.com/13697/155035878-e6305fcd-2fc7-4ae8-93da-4731c83103d0.png">

Any ideas?

**Comment by edzop** [comment]
Hi - this looks like a path issue. It's not finding the assets/ directory from the current directory. The correct behavior should be not crashing but continue the rest of the model and gracefully resume. 

I usually launch blender from console in the bpyhullgen directory while doing development so it always finds it. I could make the code more robust by finding the full directory of the script and looking more carefully to address the sub directory correctly. 

As an immediate hack to get past this - you could try copying the assets/ directory to wherever you are launching from or launch from the bpyhullgen directory then it should find it. 

Thanks for bringing this to my attention I will have some time to look at this later in the month.

**Comment by tcurdt** [comment]
Ah, good point. This looks better now

```
$ blender -P tests/hull_test_37.py 
Read prefs: /Users/tcurdt/Library/Application Support/Blender/3.1/config/userpref.blend
Integrate
WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRmattress.twin' is already linked
WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRanchor' is already linked
WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRtank_fuel_5gal' is already linked
WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRtank_fuel_5gal' is already linked
Elapsed time: 0:00:01.672
```
but I am a bit surprised by the result 🧐

<img width="1064" alt="Screenshot 2022-03-14 at 22 26 20" src="https://user-images.githubusercontent.com/13697/158264131-0616e2e3-cb4e-45c7-88cd-cf68625c09ec.png">


Is this expected?

**Comment by edzop** [comment]
Thanks for the response. This is not the expected result. I will have lots of time to look at this near the end of this month. 

The assets directory are just a static collection of "props" that are not procedurally generated but included for showing scale in relation to real world objects. 

The correct behavior should be to continue hull generation and generate a complete hull and structure. 

I will check again soon with blender 3.0 / 3.1 and make sure it works with these versions. 

As far as mac OS - I've never tried on Mac. I look forward to working with you to get it working on mac in the near future if you have time.

**Comment by tcurdt** [comment]
Happy to help.

**Comment by edzop** [comment]
I have committed some changes:
1. Update for blender 3.1
2. Update asset search path. Now it searches from relative path of script file. You should be able to execute script from any directory and it should find assets directory.

**Comment by edzop** [comment]
> Ah, good point. This looks better now
> 
> ```
> $ blender -P tests/hull_test_37.py 
> Read prefs: /Users/tcurdt/Library/Application Support/Blender/3.1/config/userpref.blend
> Integrate
> WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRmattress.twin' is already linked
> WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRanchor' is already linked
> WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRtank_fuel_5gal' is already linked
> WARN (blo.readfile): source/blender/blenloader/intern/readfile.c:4408 link_named_part: Append: ID 'GRtank_fuel_5gal' is already linked
> Elapsed time: 0:00:01.672
> ```
> 
> but I am a bit surprised by the result monocle_face
> 
> <img alt="Screenshot 2022-03-14 at 22 26 20" width="1064" src="https://user-images.githubusercontent.com/13697/158264131-0616e2e3-cb4e-45c7-88cd-cf68625c09ec.png">
> 
> Is this expected?

In the screenshot attached - the cube is the default blender cube - the test script does not delete any objects from default scene. In my development environment I delete default cube and add backdrop and some lighting meshes and save that as the default scene that way it's all ready to render. I run test script and do not have to delete default cube because it's not part of my default scene. 

The hull is actually generated correctly in the screenshot you posted - BUT the default behavior was to hide hull so only showing structural elements such as longitudinal strings and bulkheads. If you look in the outliner window in blender it shows all the objects in the scene. hull_object is hidden. The reason I previously hid the hull_object by default is when debugging development of bulkeads, keels, and longitudinal members you can't see them if the exterior hull_object (skin plates) are visible. So by hiding the hull_object by default it allowed me to focus on the other objects. 

I have changed the default behavior to not hide the hull_object so it's clearer. 

Try to pull latest code and let me know how it works...

**Comment by tcurdt** [comment]
This

    blender -P tests/hull_test_37.py

gives

<img width="1166" alt="Screenshot 2022-03-27 at 20 41 58" src="https://user-images.githubusercontent.com/13697/160295882-05853156-5148-48ee-850b-4e141f21a17b.png">

So it seems to work as expected now.

That said:
Why is the hull flat like this on both bow and stern?
Looking at the basic example I guess that's just the way the model is setup. But why?

I would like to try and create a catamaran model.
Even after skimming through the wiki I am still a bit lost.
But I guess that goes beyond this original issue. I'll close that one.
Is there a good place to ask more usage type questions?

**Comment by edzop** [comment]
I updated the wiki usage:
https://github.com/edzop/bpyhullgen/wiki/Usage
lots of new usage information added... still work in progress...

**Comment by edzop** [comment]
<img alt="Screenshot 2022-03-27 at 20 41 58" width="1166" src="https://user-images.githubusercontent.com/13697/160295882-05853156-5148-48ee-850b-4e141f21a17b.png">
> 

> That said: Why is the hull flat like this on both bow and stern? Looking at the basic example I guess that's just the way the model is setup. But why?
I just added explanation to this question at bottom of:
https://github.com/edzop/bpyhullgen/wiki/Usage

I have also updated tests/hull_test_37.py so the design is a little less square on the ends...
